routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;




Route::get('/', 'HomeController@index')->name('home');

Route::get('/courses/{courseSlug}', 'CourseController@single')->name('home.course.single');
Route::get('/courses','CourseController@all')->name('home.course.all');
Route::middleware(['auth'])->get('/download/{episode}','CourseController@downloadVideo');
Route::middleware(['auth'])->post('/payment/course','CourseController@payment')->name('payment.course');
Route::middleware(['auth'])->get('/payment/callback','CourseController@paymentCallback')->name('payment.callback');

Route::get('/articles/{articleSlug}', 'ArticleController@single')->name('home.article.single');
Route::get('/articles', 'ArticleController@all')->name('home.article.all');
Route::get('/contact-us', 'HomeController@contact')->name('home.contact');
Route::get('/categories', 'HomeController@categories')->name('home.categories');
Route::get('/about-us', 'HomeController@about')->name('home.about');
Route::post('/search', 'HomeController@searchAjax')->name('home.search.ajax');

Route::middleware(['auth'])->post('/comments','HomeController@storeComment')->name('home.comment.store');
Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'],'prefix' => 'profile' , 'as' => 'user.'],function () {
    Route::get('/','ProfileController@index')->name('profile');
    Route::get('/history','ProfileController@history')->name('profile.history');
    Route::get('/vip','ProfileController@vip')->name('profile.vip');
    Route::post('/vip/payment','ProfileController@payment')->name('profile.vip.payment');
    Route::get('/vip/payment/callback','ProfileController@paymentCallback')->name('profile.vip.payment.callback');
});

Route::middleware(['auth','isUserAdmin','verified'])->namespace('Admin')->prefix('admin')->group(function () {


    //Articles Routes
    Route::resource('articles','ArticleController');

    // Courses Routes
    Route::get('/courses/episodes/{course}','CourseController@episodes')->name('courses.episodes');
    Route::resource('courses','CourseController');
    // Episodes Routes
    Route::resource('episodes','EpisodeController');

    // Categories Routes
    Route::resource('categories','CategoryController');

    // Roles And Permissions
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');

    // Comments Routes
    Route::get('/comments/confirm/{comment}','CommentController@confirm')->name('comments.confirm');
    Route::get('/comments/approved','CommentController@approvedIndex')->name('comments.approvedIndex');
    Route::resource('comments','CommentController');

    // Payments Routes
    Route::get('/payments','PaymentController@index')->name('payments.index');

    // Others Routes
    Route::get('/','PanelController@index');
    Route::post('/panel/fileUpload','PanelController@uploadImageSubject');


    Route::group(['prefix' => 'users'],function () {
        Route::get('/','UserController@index')->name('users.all');
        Route::delete('/{user}','UserController@destroy')->name('users.destroy');
        Route::get('/{user}/levelChange','UserController@levelChange')->name('users.levelChange');
        Route::middleware('redirectIfLevelNotAdmin')->
        get('/{user}/roles','UserController@userRoleIndex')->name('users.rolesIndex');
        Route::middleware('redirectIfLevelNotAdmin')->
        post('/{user}/roles','UserController@userRole')->name('users.roles');
    });
});



Route::group([
    'namespace' => 'Auth'
],function () {
// Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    //login with google
    Route::get('login/google', 'LoginController@redirectToProvider')->name('login.google');
    Route::get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    // RestPassword Routes...s
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
    // Verify Email Routes...
    Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');



});

Route::get('/verify/googleRecaptcha','HomeController@verifyGoogleRecaptcha')->name('verification.recaptcha');

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Role
 *
 * @property int $id
 * @property string $name
 * @property string|null $label
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Permission[] $permissions
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\User[] $users
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role whereLabel($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Role whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Role extends Model
{
    protected $fillable = [
        'name', 'label'
    ];

    public function users()
    {
        return $this->belongsToMany(User::class);
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class);
    }
}

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Permission;
use App\Role;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $roles = Role::latest()->paginate(10);
        return view('Admin.roles.all',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissions = Permission::latest()->get();
        return view('Admin.roles.create',compact('permissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request , [
            'name' => 'required',
            'label' => 'required'
        ]);

        $role = Role::create($request->all());
        $role->permissions()->sync($request->permissions);
        return redirect(route('roles.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function show(Role $role)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        return view('Admin.roles.edit',compact('role'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Role  $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        Role::destroy($role->id);
        return redirect(route('roles.index'));
    }

}

resources/views/Admin/roles/all.blade.php
@extends('Admin.master')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">نقش ها</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('roles.create')}}" class="btn btn-primary">افزودن نقش</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">
        @include('Admin.section.flash')
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">لیست نقش ها</h3>
            </div>
            <!-- /.card-header -->

            @if($roles->count() > 0)
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <tbody><tr>
                            <th style="width: 10px">#</th>
                            <th>نام</th>
                            <th>برچسب</th>
                            <th>تنظیمات</th>
                        </tr>
                        @foreach($roles as $key => $role)
                            <tr>
                                <td>{{$key + 1}}.</td>
                                <td>{{ $role->name  }}</td>
                                <td>
                                    {{$role->label}}
                                </td>
                                <td>
                                    <form action="{{route('roles.destroy',$role->id)}}" method="post">
                                        @method('delete')
                                        @csrf
                                        <div class="btn-group" role="group" aria-label="Basic example">
                                            <a href="{{route('roles.edit',$role->id)}}" class="btn btn-sm btn-info btn-flat">
                                                <span class="material-icons">edit</span>
                                            </a>
                                            <button type="submit" class="btn btn-sm btn-danger btn-flat"><span class="material-icons">delete</span></button>
                                        </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody></table>
                </div>
                {{$roles->render()}}
            @else
                <div class="callout callout-warning m-4" role="alert">
                    موردی یافت نشد
                </div>
        @endif

        <!-- /.card-body -->
        </div>
    </div>


@endsection

resources/views/Admin/roles/create.blade.php
@extends('Admin.master')



@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">نقش ها</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('roles.index')}}" class="btn btn-secondary">لیست نقش ها</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">

        @include('Admin.section.errors')

        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">افزودن نقش</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <form action="{{route('roles.store')}}" method="post" role="form">
                @csrf
                   <div class="m-3">
                       <div class="row">
                           <div class="col-6">
                               <div class="form-group">
                                   <label for="body">نام </label>
                                   <input type="text" name="name" class="form-control" id="name" value="{{old('name')}}" placeholder="نام را وارد کنید">
                               </div>

                           </div>
                           <div class="col-6">
                               <div class="form-group">
                                   <label for="label"> برچسب </label>
                                   <input type="text" name="label" class="form-control" id="label" value="{{old('label')}}" placeholder="برچسب را وارد کنید">
                               </div>
                           </div>
                       </div>
                       <div class="form-group">
                           <label for="title">اجازه دسترسی به</label>

                           <select class="form-control selectpicker" name="permissions[]" multiple>
                               @foreach ($permissions as $permission)
                                   <option value="{{$permission->id}}">{{$permission->label}}</option>
                               @endforeach

                           </select>
                       </div>
                   </div>

                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/Admin/roles/edit.blade.php
@extends('Admin.master')



@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">نقش ها</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('roles.index')}}" class="btn btn-secondary">لیست نقش ها</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">

        @include('Admin.section.errors')

        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">ویرایش نقش</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <form action="{{route('roles.update')}}" method="post" role="form">
                @csrf
                   <div class="m-3">
                       <div class="row">
                           <div class="col-6">
                               <div class="form-group">
                                   <label for="body">نام </label>
                                   <input type="text" name="name" class="form-control" id="name" value="{{old($role->name,'name')}}" placeholder="نام را وارد کنید">
                               </div>

                           </div>
                           <div class="col-6">
                               <div class="form-group">
                                   <label for="label"> برچسب </label>
                                   <input type="text" name="label" class="form-control" id="label" value="{{old($role->name,'label')}}" placeholder="برچسب را وارد کنید">
                               </div>
                           </div>
                       </div>
                   </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            </form>
        </div>
    </div>

@endsection