routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;




Route::get('/', 'HomeController@index')->name('home');

Route::get('/courses/{courseSlug}', 'CourseController@single')->name('home.course.single');
Route::get('/courses','CourseController@all')->name('home.course.all');
Route::middleware(['auth'])->get('/download/{episode}','CourseController@downloadVideo');
Route::middleware(['auth'])->post('/payment/course','CourseController@payment')->name('payment.course');
Route::middleware(['auth'])->get('/payment/callback','CourseController@paymentCallback')->name('payment.callback');

Route::get('/articles/{articleSlug}', 'ArticleController@single')->name('home.article.single');
Route::get('/articles', 'ArticleController@all')->name('home.article.all');
Route::get('/contact-us', 'HomeController@contact')->name('home.contact');
Route::get('/categories', 'HomeController@categories')->name('home.categories');
Route::get('/about-us', 'HomeController@about')->name('home.about');
Route::post('/search', 'HomeController@searchAjax')->name('home.search.ajax');

Route::middleware(['auth'])->post('/comments','HomeController@storeComment')->name('home.comment.store');
Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'],'prefix' => 'profile' , 'as' => 'user.'],function () {
    Route::get('/','ProfileController@index')->name('profile');
    Route::get('/history','ProfileController@history')->name('profile.history');
    Route::get('/vip','ProfileController@vip')->name('profile.vip');
    Route::post('/vip/payment','ProfileController@payment')->name('profile.vip.payment');
    Route::get('/vip/payment/callback','ProfileController@paymentCallback')->name('profile.vip.payment.callback');
});

Route::middleware(['auth','isUserAdmin','verified'])->namespace('Admin')->prefix('admin')->group(function () {


    //Articles Routes
    Route::resource('articles','ArticleController');

    // Courses Routes
    Route::get('/courses/episodes/{course}','CourseController@episodes')->name('courses.episodes');
    Route::resource('courses','CourseController');
    // Episodes Routes
    Route::resource('episodes','EpisodeController');

    // Categories Routes
    Route::resource('categories','CategoryController');

    // Roles And Permissions
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');

    // Comments Routes
    Route::get('/comments/confirm/{comment}','CommentController@confirm')->name('comments.confirm');
    Route::get('/comments/approved','CommentController@approvedIndex')->name('comments.approvedIndex');
    Route::resource('comments','CommentController');

    // Payments Routes
    Route::get('/payments','PaymentController@index')->name('payments.index');

    // Others Routes
    Route::get('/','PanelController@index');
    Route::post('/panel/fileUpload','PanelController@uploadImageSubject');


    Route::group(['prefix' => 'users'],function () {
        Route::get('/','UserController@index')->name('users.all');
        Route::delete('/{user}','UserController@destroy')->name('users.destroy');
        Route::get('/{user}/levelChange','UserController@levelChange')->name('users.levelChange');
        Route::middleware('redirectIfLevelNotAdmin')->
        get('/{user}/roles','UserController@userRoleIndex')->name('users.rolesIndex');
        Route::middleware('redirectIfLevelNotAdmin')->
        post('/{user}/roles','UserController@userRole')->name('users.roles');
    });
});



Route::group([
    'namespace' => 'Auth'
],function () {
// Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    //login with google
    Route::get('login/google', 'LoginController@redirectToProvider')->name('login.google');
    Route::get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    // RestPassword Routes...s
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
    // Verify Email Routes...
    Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');



});

Route::get('/verify/googleRecaptcha','HomeController@verifyGoogleRecaptcha')->name('verification.recaptcha');

resources/views/Admin/section/errors.blade.php
@if($errors->any())

    <div class="alert alert-warning alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fa fa-ban"></i> توجه!</h5>
        <div class="d-flex flex-column justify-content-around">
            @foreach($errors->all() as $key => $error)

                <div>{{$key + 1}}. {{$error}}</div>
            @endforeach
        </div>

    </div>
@endif

resources/views/Admin/section/flash.blade.php
@if(Session::has('message'))
    <div class="callout {{ Session::get('alert-class', 'callout-info')}}">
        <p class="alert ">{{ Session::get('message') }}</p>
    </div>
@endif

resources/views/Admin/section/nav.blade.php
<nav class="main-header navbar navbar-expand elevation-1 bg-dark navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="material-icons md-light">menu</i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/" class="nav-link">خانه</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{route('home.contact')}}" class="nav-link">تماس</a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="جستجو" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav mr-auto">
        <!-- Messages Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa fa-comments-o"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">

                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                حسام موسوی
                                <span class="float-left text-sm text-danger"><i class="fa fa-star"></i></span>
                            </h3>
                            <p class="text-sm">با من تماس بگیر لطفا...</p>
                            <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 ساعت قبل</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle ml-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                پیمان احمدی
                                <span class="float-left text-sm text-muted"><i class="fa fa-star"></i></span>
                            </h3>
                            <p class="text-sm">من پیامتو دریافت کردم</p>
                            <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i> 4 ساعت قبل</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle ml-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                سارا وکیلی
                                <span class="float-left text-sm text-warning"><i class="fa fa-star"></i></span>
                            </h3>
                            <p class="text-sm">پروژه اتون عالی بود مرسی واقعا</p>
                            <p class="text-sm text-muted"><i class="fa fa-clock-o mr-1"></i>4 ساعت قبل</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">مشاهده همه پیام‌ها</a>
            </div>
        </li>
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa fa-bell-o"></i>
                <span class="badge badge-warning navbar-badge">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
                <span class="dropdown-item dropdown-header">15 نوتیفیکیشن</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-envelope ml-2"></i> 4 پیام جدید
                    <span class="float-left text-muted text-sm">3 دقیقه</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-users ml-2"></i> 8 درخواست دوستی
                    <span class="float-left text-muted text-sm">12 ساعت</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fa fa-file ml-2"></i> 3 گزارش جدید
                    <span class="float-left text-muted text-sm">2 روز</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">مشاهده همه نوتیفیکیشن</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
                    class="fa fa-th-large"></i></a>
        </li>
    </ul>
</nav>

resources/views/Admin/section/sidebar.blade.php
<aside class="main-sidebar sidebar-light-warning elevation-3">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="/images/lock-open.png" width="32" alt="" srcset="">
        <span class="brand-text font-weight-light">پنل مدیریت</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->
                    {{--<li class="nav-item has-treeview menu-close">
                        <a href="#" class="nav-link active">
                            <i class="material-icons">dashboard</i>
                            <p>
                                صفحات شروع
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="#" class="nav-link active">
                                    <i class="material-icons">check_circle_outline</i>
                                    <p>صفحه فعال</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fa fa-circle-o nav-icon"></i>
                                    <p>صفحه غیر فعال</p>
                                </a>
                            </li>
                        </ul>
                    </li>--}}
                    <li class="nav-item">
                        <a href="#" class="nav-link
                            @if( Request::getPathInfo() ==='/admin')
                            active
                            @endif">
                            <i class="material-icons">dashboard</i>
                            <p>
                                پیشخوان
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('articles.index')}}" class="nav-link
                            @if( Request::fullUrl() ===route('articles.index'))
                            active
                            @endif
                            ">
                            <i class="material-icons">description</i>
                            <p>
                                مقالات
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('courses.index')}}" class="nav-link
                            @if( Request::fullUrl() ===route('courses.index'))
                            active
                            @endif
                            ">
                            <i class="material-icons">library_books</i>
                            <p>
                               دوره ها
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('categories.index')}}" class="nav-link
                            @if( Request::fullUrl() ===route('categories.index'))
                            active
                            @endif
                            ">
                            <i class="material-icons">dynamic_feed</i>
                            <p> دسته بندی</p>
                        </a>
                    </li>
                    <li class="nav-item   has-treeview menu-close">
                        <a href="#" class="nav-link
                            @if( Request::fullUrl() === route('permissions.index') || 
                                 Request::fullUrl() === route('roles.index'))
                            active
                            @endif
                            ">
                            <i class="material-icons">vpn_key</i>
                            <p>
                            سطوح دسترسی
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="{{ route('permissions.index') }}" class="nav-link active">
                                    
                                    <p>اجازه دسترسی</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ route('roles.index') }}" class="nav-link active">
                                    <p>نقش ها</p>
                                </a>
                            </li>
                        </ul>

                    </li>
                    <li class="nav-item">
                        <a href="{{route('comments.approvedIndex')}}" class="nav-link
                            @if( Request::fullUrl() ===route('comments.approvedIndex'))
                            active
                            @endif
                            ">
                            <i class="material-icons">chat_bubble</i>
                            <p>
                               کامنت ها
                               <span class="badge badge-pill badge-danger">{{ $newCommentCount }}</span>
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{{route('payments.index')}}" class="nav-link
                            @if( Request::fullUrl() ===route('payments.index'))
                            active
                            @endif
                            ">
                            <i class="material-icons">payment</i>
                            <p>
                              تراکنش ها
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
    </div>
    <!-- /.sidebar -->
</aside>