routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;




Route::get('/', 'HomeController@index')->name('home');

Route::get('/courses/{courseSlug}', 'CourseController@single')->name('home.course.single');
Route::get('/courses','CourseController@all')->name('home.course.all');
Route::middleware(['auth'])->get('/download/{episode}','CourseController@downloadVideo');
Route::middleware(['auth'])->post('/payment/course','CourseController@payment')->name('payment.course');
Route::middleware(['auth'])->get('/payment/callback','CourseController@paymentCallback')->name('payment.callback');

Route::get('/articles/{articleSlug}', 'ArticleController@single')->name('home.article.single');
Route::get('/articles', 'ArticleController@all')->name('home.article.all');
Route::get('/contact-us', 'HomeController@contact')->name('home.contact');
Route::get('/categories', 'HomeController@categories')->name('home.categories');
Route::get('/about-us', 'HomeController@about')->name('home.about');
Route::post('/search', 'HomeController@searchAjax')->name('home.search.ajax');

Route::middleware(['auth'])->post('/comments','HomeController@storeComment')->name('home.comment.store');
Auth::routes(['verify' => true]);

Route::group(['middleware' => ['auth'],'prefix' => 'profile' , 'as' => 'user.'],function () {
    Route::get('/','ProfileController@index')->name('profile');
    Route::get('/history','ProfileController@history')->name('profile.history');
    Route::get('/vip','ProfileController@vip')->name('profile.vip');
    Route::post('/vip/payment','ProfileController@payment')->name('profile.vip.payment');
    Route::get('/vip/payment/callback','ProfileController@paymentCallback')->name('profile.vip.payment.callback');
});

Route::middleware(['auth','isUserAdmin','verified'])->namespace('Admin')->prefix('admin')->group(function () {


    //Articles Routes
    Route::resource('articles','ArticleController');

    // Courses Routes
    Route::get('/courses/episodes/{course}','CourseController@episodes')->name('courses.episodes');
    Route::resource('courses','CourseController');
    // Episodes Routes
    Route::resource('episodes','EpisodeController');

    // Categories Routes
    Route::resource('categories','CategoryController');

    // Roles And Permissions
    Route::resource('roles','RoleController');
    Route::resource('permissions','PermissionController');

    // Comments Routes
    Route::get('/comments/confirm/{comment}','CommentController@confirm')->name('comments.confirm');
    Route::get('/comments/approved','CommentController@approvedIndex')->name('comments.approvedIndex');
    Route::resource('comments','CommentController');

    // Payments Routes
    Route::get('/payments','PaymentController@index')->name('payments.index');

    // Others Routes
    Route::get('/','PanelController@index');
    Route::post('/panel/fileUpload','PanelController@uploadImageSubject');


    Route::group(['prefix' => 'users'],function () {
        Route::get('/','UserController@index')->name('users.all');
        Route::delete('/{user}','UserController@destroy')->name('users.destroy');
        Route::get('/{user}/levelChange','UserController@levelChange')->name('users.levelChange');
        Route::middleware('redirectIfLevelNotAdmin')->
        get('/{user}/roles','UserController@userRoleIndex')->name('users.rolesIndex');
        Route::middleware('redirectIfLevelNotAdmin')->
        post('/{user}/roles','UserController@userRole')->name('users.roles');
    });
});



Route::group([
    'namespace' => 'Auth'
],function () {
// Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    //login with google
    Route::get('login/google', 'LoginController@redirectToProvider')->name('login.google');
    Route::get('login/google/callback', 'LoginController@handleProviderCallback');
    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');
    // RestPassword Routes...s
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
    // Verify Email Routes...
    Route::get('email/verify', 'VerificationController@show')->name('verification.notice');
    Route::get('email/verify/{id}', 'VerificationController@verify')->name('verification.verify');
    Route::get('email/resend', 'VerificationController@resend')->name('verification.resend');



});

Route::get('/verify/googleRecaptcha','HomeController@verifyGoogleRecaptcha')->name('verification.recaptcha');

resources/views/Admin/courses/all.blade.php
@extends('Admin.master')

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">دوره ها</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('courses.create')}}" class="btn btn-primary">افزودن دوره</a>
                    <a href="{{route('episodes.index')}}" class="btn btn-danger">همه ویدئو</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">
        @include('Admin.section.flash')
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">دوره</h3>
            </div>
            <!-- /.card-header -->

            @if($courses->count() > 0)
                <div class="card-body p-0">
                    <table class="table table-striped">
                        <tbody><tr>
                            <th style="width: 10px">#</th>
                            <th>موضوع</th>
                            <th>تاریخ ارسال</th>
                            <th>زمان</th>
                            <th>بازدید</th>
                            <th>کامنت</th>
                            <th>تنظیمات</th>
                        </tr>
                        @foreach($courses as $key => $course)
                            <tr>
                                <td>{{$key + 1}}.</td>
                                <td>{{ $course->title  }}</td>
                                <td>
                                    {{ jdate($course->created_at)->format('%A, %d %B %y')  }}
                                </td>
                                <td>{{ $course->time  }}</td>
                                <td>{{ $course->viewCount  }}</td>
                                <td>{{ $course->commentCount  }}</td>
                                <td>
                                    <form action="{{route('courses.destroy',['id' => $course->id])}}" method="post">
                                        @method('delete')
                                        @csrf
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a href="{{route('courses.episodes',$course->id)}}" class="btn btn-sm btn-info btn-flat">
                                            <span class="material-icons">switch_video</span>
                                        </a>
                                        <a href="{{route('courses.edit',$course->id)}}" class="btn btn-sm btn-info btn-flat">
                                            <span class="material-icons">edit</span>
                                        </a>
                                        <button type="submit" class="btn btn-sm btn-danger btn-flat"><span class="material-icons">delete</span></button>
                                    </div>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody></table>
            </div>
            @else
                <div class="callout callout-warning m-4" role="alert">
                  موردی یافت نشد
                </div>
        @endif
            <div class="text-center">
                {{ $courses->render()  }}
            </div>
            <!-- /.card-body -->
        </div>
    </div>

    
@endsection

resources/views/Admin/courses/create.blade.php
@extends('Admin.master')

@section('scripts')
    <script src="/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('body',{
            filebrowserBrowseUrl: '/admin/panel/fileUpload?&_token={{csrf_token()}}',
            filebrowserUploadUrl: '/admin/panel/fileUpload?&_token={{csrf_token()}}'
        });
    </script>

@endsection

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">مقالات</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('articles.index')}}" class="btn btn-secondary">لیست مقالات</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">

        @include('Admin.section.errors')

        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">افزودن دوره</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <form action="{{route('courses.store')}}" method="post" enctype="multipart/form-data" role="form">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">موضوع</label>
                        <input type="text" name="title" class="form-control" id="title" value="{{old('title')}}" placeholder="موضوع را وارد کنید">
                    </div>
                    <div class="form-group">
                        <label for="title">نوع دوره</label>

                        <select class="form-control selectpicker" name="type">
                            <option value="free" selected>رایگان</option>
                            <option value="vip">ویژه</option>
                            <option value="cash">نقدی</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="title">دسته بندی های مربوطه</label>

                        <select class="form-control selectpicker"  data-live-search="true" name="categories[]" multiple>
                        @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach

                        </select>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">انتخاب عکس</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="images" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">انتخاب عکس مقاله</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="body">متن اصلی</label>
                        <textarea  class="form-control" name="body" id="body" rows="5" >{{old('body')}}</textarea>
                    </div>
                    <div class="form-group">

                        <div class="row">
                            <div class="col-lg-6 col-sm-12">
                                <label for="price">قیمت</label>
                                <input type="text" name="price" class="form-control" id="price" value="{{old('price',0)}}" placeholder="قیمت را وارد کنید">
                            </div>
                            <div class="col-lg-6 col-sm-12">
                                <label for="tags">تگ ها</label>
                                <input type="text" name="tags" class="form-control" id="tags" value="{{old('tags')}}" placeholder="تگ ها را وارد کنید">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            </form>
        </div>
    </div>

@endsection

resources/views/Admin/courses/edit.blade.php
@extends('Admin.master')

@section('scripts')
    <script src="/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('body',{
            filebrowserBrowseUrl: '/admin/panel/fileUpload?&_token={{csrf_token()}}',
            filebrowserUploadUrl: '/admin/panel/fileUpload?&_token={{csrf_token()}}'
        });
    </script>

@endsection

@section('content')

    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="">
            <div class="d-flex justify-content-between mb-2">
                <div class="">
                    <h1 class="m-0 font-size-3 text-dark">دوره ها</h1>
                </div><!-- /.col -->
                <div class="">
                    <a href="{{route('articles.index')}}" class="btn btn-secondary">لیست مقالات</a>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="container-fluid">

        @include('Admin.section.errors')

        <div class="card card-info">
            <div class="card-header">
                <h3 class="card-title">افزودن دوره</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->

            <form action="{{route('courses.update',['id' => $course->id])}}" method="post" enctype="multipart/form-data" role="form">
                @csrf
                @method('PUT')
                <div class="card-body">
                    <div class="form-group">
                        <label for="title">موضوع</label>
                        <input type="text" name="title" class="form-control" id="title" value="{{old('title',$course->title)}}" placeholder="موضوع را وارد کنید">
                    </div>
                    <div class="form-group">
                        <label for="title">نوع دوره</label>

                        <select class="form-control selectpicker" name="type">
                            <option value="free" {{$course->type === 'free' ?? 'selected' }}>رایگان</option>
                            <option value="vip" {{$course->type === 'vip' ?? 'selected' }}>ویژه</option>
                            <option value="cash" {{$course->type === 'cash' ?? 'selected' }}>نقدی</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="title">دسته بندی های مربوطه</label>

                        <select class="form-control selectpicker"  data-live-search="true" name="categories[]" multiple>
                            @foreach ($categories as $category)
                                <option value="{{$category->id}}">{{$category->name}}</option>
                            @endforeach

                        </select>
                    </div>

                    <div class="p-3 d-flex">
                        <span class="pl-2">عکس دوره:</span>
                        <img class="rounded" src="{{$course->images['240']}}" alt="">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputFile">انتخاب عکس مجدد</label>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" name="images" class="custom-file-input" id="exampleInputFile">
                                <label class="custom-file-label" for="exampleInputFile">انتخاب عکس دوره</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="body">متن اصلی</label>
                        <textarea  class="form-control" name="body" id="body" rows="5" >{{old('body',$course->body)}}</textarea>
                    </div>
                    <div class="form-group">

                        <div class="row">
                            <div class="col-lg-6 col-sm-12">
                                <label for="price">قیمت</label>
                                <input type="text" name="price" class="form-control" id="price" value="{{old('price',$course->price)}}" placeholder="قیمت را وارد کنید">
                            </div>
                            <div class="col-lg-6 col-sm-12">
                                <label for="tags">تگ ها</label>
                                <input type="text" name="tags" class="form-control" id="tags" value="{{old('tags',$course->tags)}}" placeholder="تگ ها را وارد کنید">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">ارسال</button>
                </div>
            </form>
        </div>
    </div>

@endsection